### ISSUE TITLE
build, run for windows

### ISSUE THREAD

**Issue by hoangvannam1690** [bit-shift-io/audiobook#1]
hi, can you help me install & using taglib for windows.

**Comment by Gibbz** [comment]
Hi,
I have no clue if this works on windows. It uses cmake to build, or you can also use qmake (qt creator).
I found this after a quick search, it may help you.
https://www.joelverhagen.com/blog/2010/11/how-to-compile-taglib-on-windows/

**Comment by Gibbz** [comment]
Just to let you know, I have ported audiobook to qml, and included taglib in the source directory. 
It now builds on windows.
